# Generated by Django 4.1.6 on 2023-04-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('flight_price', models.FloatField()),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='smash_airline.airport')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='smash_airline.airport')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerSeatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('first_name', models.CharField(blank=True, default=None, max_length=25)),
                ('surname', models.CharField(blank=True, default=None, max_length=25)),
                ('seat_class', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('passenger_type', models.CharField(blank=True, default=None, max_length=10)),
                ('reserved', models.BooleanField(default=False)),
                ('booking_id', models.IntegerField(blank=True, default=None, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smash_airline.flightinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='booking', serialize=False, to='smash_airline.passengerseatinfo')),
                ('passenger_type', models.CharField(blank=True, default=None, max_length=25)),
                ('email', models.CharField(default=None, max_length=50)),
                ('transaction_id', models.IntegerField(default=None)),
                ('number_tickets', models.IntegerField(default=None)),
                ('seat_class', models.CharField(default=None, max_length=20)),
                ('total_price', models.FloatField(default=None)),
                ('cancelled', models.BooleanField(default=False)),
                ('seat_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='smash_airline.passengerseatinfo')),
            ],
        ),
    ]
