# Generated by Django 4.1.6 on 2023-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
