# Generated by Django 4.1.6 on 2023-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_airline', '0002_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
