# Generated by Django 4.1.6 on 2023-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smash_airline', '0003_alter_booking_passenger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_tickets',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
