# Generated by Django 4.1.6 on 2023-05-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smash_airline', '0007_alter_passengerseatinfo_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_codes',
        ),
    ]
