# Generated by Django 4.1.6 on 2023-05-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smash_airline', '0008_remove_booking_seat_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerseatinfo',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smash_airline.booking'),
        ),
    ]
